image: python:3.7.1

stages:
  - test
  - deploy

services:
  - name: timescale/timescaledb:latest-pg9.6
    alias: db

before_script:
  - pip install -r requirements.txt

unittest:
  stage: test
  script:
    - python manage.py db upgrade
    - python -m pytest tests
  variables:
    POSTGRES_DB: "muepy_test"
    POSTGRES_HOST: "db"
    POSTGRES_PORT: "5432"
    POSTGRES_USER: "postgres"
    POSTGRES_PASSWORD: "postgres"
  tags:
    - test

deploy:
  stage: deploy
  script:
    - python manage.py db upgrade
    - git push azure HEAD:master
  environment:
    name: production
  only:
    - master

