version: '2'
services:
  db:
    image: timescale/timescaledb:latest-pg9.6
    ports:
      - "6868:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - /var/lib/postgres
